In [1]:
#四个时间步
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
inputwords="abcde"
w_to_id={"a":0,"b":1,"c":2,"d":3,"e":4}
id_to_onehot={0:[1,0,0,0,0],1:[0,1,0,0,0],2:[0,0,1,0,0],3:[0,0,0,1,0],4:[0,0,0,0,1]}
train_x=[
    [id_to_onehot[w_to_id["a"]],id_to_onehot[w_to_id["b"]],id_to_onehot[w_to_id["c"]],id_to_onehot[w_to_id["d"]]]
,[id_to_onehot[w_to_id["b"]],id_to_onehot[w_to_id["c"]],id_to_onehot[w_to_id["d"]],id_to_onehot[w_to_id["e"]]],
 [id_to_onehot[w_to_id["c"]],id_to_onehot[w_to_id["d"]],id_to_onehot[w_to_id["e"]],id_to_onehot[w_to_id["a"]]],
[id_to_onehot[w_to_id["d"]],id_to_onehot[w_to_id["e"]],id_to_onehot[w_to_id["a"]],id_to_onehot[w_to_id["b"]]],
[id_to_onehot[w_to_id["e"]],id_to_onehot[w_to_id["a"]],id_to_onehot[w_to_id["b"]],id_to_onehot[w_to_id["c"]]]
]
train_y=[w_to_id["e"],w_to_id["a"],w_to_id["b"],w_to_id["c"],w_to_id["d"]]
train_y=np.array(train_y)
train_x=np.reshape(train_x,(len(train_x),4,5))
train_x=train_x.astype(np.float)
print(train_x)
print(train_y)
print(train_x.shape)
print(train_y.shape)

[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]]

 [[0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]]
[4 0 1 2 3]
(5, 4, 5)
(5,)


In [2]:
import os
np.random.seed(7)
np.random.shuffle(train_x)
np.random.seed(7)
np.random.shuffle(train_y)

In [3]:
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.SimpleRNN(5))
model.add(tf.keras.layers.Dense(units=5,activation="softmax"))
checkpoint_save_path="./字符预测/checkpoint_save2"
if os.path.exists(checkpoint_save_path+".index"):
    print("----load model---")
    model.load_weights(checkpoint_save_path)
pre_one_char_callbacks=tf.keras.callbacks.ModelCheckpoint(filepath=
                                                          checkpoint_save_path,
                                                          save_best_only=True,
                                                          save_weights_only=True,
                                                          monitor='loss')
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=["accuracy"]
             )
train_history = model.fit(train_x,train_y,
                          batch_size=32, 
                          epochs=100, 
                          callbacks=[pre_one_char_callbacks])
print(train_history)          

----load model---
Train on 5 samples
Epoch 1/100
5/5 [==============================] - 4s 751ms/sample - loss: 0.0795 - accuracy: 1.0000
Epoch 2/100
5/5 [==============================] - 0s 50ms/sample - loss: 0.0779 - accuracy: 1.0000
Epoch 3/100
5/5 [==============================] - 0s 50ms/sample - loss: 0.0762 - accuracy: 1.0000
Epoch 4/100
5/5 [==============================] - 0s 50ms/sample - loss: 0.0746 - accuracy: 1.0000
Epoch 5/100
5/5 [==============================] - 0s 51ms/sample - loss: 0.0731 - accuracy: 1.0000
Epoch 6/100
5/5 [==============================] - 1s 116ms/sample - loss: 0.0716 - accuracy: 1.0000
Epoch 7/100
5/5 [==============================] - 0s 54ms/sample - loss: 0.0702 - accuracy: 1.0000
Epoch 8/100
5/5 [==============================] - 0s 52ms/sample - loss: 0.0688 - accuracy: 1.0000
Epoch 9/100
5/5 [==============================] - 0s 54ms/sample - loss: 0.0675 - accuracy: 1.0000
Epoch 10/100
5/5 [==============================] - 0s 55ms/s

Epoch 82/100
5/5 [==============================] - 0s 61ms/sample - loss: 0.0260 - accuracy: 1.0000
Epoch 83/100
5/5 [==============================] - 0s 66ms/sample - loss: 0.0258 - accuracy: 1.0000
Epoch 84/100
5/5 [==============================] - 0s 48ms/sample - loss: 0.0256 - accuracy: 1.0000
Epoch 85/100
5/5 [==============================] - 0s 62ms/sample - loss: 0.0253 - accuracy: 1.0000
Epoch 86/100
5/5 [==============================] - 0s 51ms/sample - loss: 0.0251 - accuracy: 1.0000
Epoch 87/100
5/5 [==============================] - 0s 48ms/sample - loss: 0.0249 - accuracy: 1.0000
Epoch 88/100
5/5 [==============================] - 0s 48ms/sample - loss: 0.0247 - accuracy: 1.0000
Epoch 89/100
5/5 [==============================] - 0s 51ms/sample - loss: 0.0245 - accuracy: 1.0000
Epoch 90/100
5/5 [==============================] - 0s 84ms/sample - loss: 0.0242 - accuracy: 1.0000
Epoch 91/100
5/5 [==============================] - 0s 51ms/sample - loss: 0.0240 - accurac

In [ ]:
# 参数的提取
with open("./字符预测/weights2.txt","a") as fp:
    for r in model.trainable_variables:
        fp.write(str(r.name)+"\n")
        fp.write(str(r.shape)+"\n")
        fp.write(str(r.numpy())+"\n")

In [6]:
pre_num=eval(input())
for i in range(pre_num):
    alphet=input("请输入字母:")
    alphet=[id_to_onehot[w_to_id[alphet[0]]],
            id_to_onehot[w_to_id[alphet[1]]],
            id_to_onehot[w_to_id[alphet[2]]],
            id_to_onehot[w_to_id[alphet[3]]]]
    alphet=np.reshape(alphet,(1,4,5))
    prediction=model.predict(alphet)
    print("预测值："+inputwords[np.argmax(prediction)])

3
请输入字母:abcd
预测值：e
请输入字母:bcde
预测值：a
请输入字母:cdea
预测值：b
