In [4]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
w_to_id=[chr(i) for i in np.arange(97,97+26)]
training_set_scaled=np.arange(26)
w_to_id=dict(zip(w_to_id,training_set_scaled))
train_x=[]
train_y=[]
for i in range(4, 26):
    train_x.append(training_set_scaled[i - 4:i])
    train_y.append(training_set_scaled[i])
train_x=np.reshape(train_x,(len(train_x),4))
train_y=np.array(train_y)
print(train_x)
print(len(train_x))
print(train_y)
print(train_x.shape)

[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]]
22
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
(22, 4)


In [36]:
np.random.seed(7)
np.random.shuffle(train_x)
np.random.seed(7)
np.random.shuffle(train_y)
tf.random.set_seed(7)

In [37]:
# model = tf.keras.Sequential([
#     tf.keras.layers.Embedding(26, 2),
#     tf.keras.layers.SimpleRNN(10),
#     tf.keras.layers.Dense(26, activation='softmax')
# ])
model=tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(26,2,))
model.add(tf.keras.layers.SimpleRNN(5))
model.add(tf.keras.layers.Dense(units=26,activation="softmax"))
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)
            ,metrics=["accuracy"]
             )
checkpoint_save_path="./字符预测/Embedding/many_time_step"
if os.path.exists(checkpoint_save_path+".index"):
    print("-----load model-----")
    model.load_weights(checkpoint_save_path)
many_time_step_callbacks=tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_save_path,
                                                  save_best_only=True,
                                                 save_weights_only=True,
                                                 monitor="loss")
train_history=model.fit(train_x,train_y,
                          batch_size=32, 
                          epochs=100, 
                          callbacks=[many_time_step_callbacks])
print(train_history)

-----load model-----
Train on 22 samples
Epoch 1/100
22/22 [==============================] - 4s 175ms/sample - loss: 0.8076 - accuracy: 0.8636
Epoch 2/100
22/22 [==============================] - 0s 11ms/sample - loss: 0.7969 - accuracy: 0.8636
Epoch 3/100
22/22 [==============================] - 0s 12ms/sample - loss: 0.7865 - accuracy: 0.8636
Epoch 4/100
22/22 [==============================] - 0s 12ms/sample - loss: 0.7763 - accuracy: 0.8636
Epoch 5/100
22/22 [==============================] - 1s 24ms/sample - loss: 0.7664 - accuracy: 0.8636
Epoch 6/100
22/22 [==============================] - 0s 12ms/sample - loss: 0.7566 - accuracy: 0.8636
Epoch 7/100
22/22 [==============================] - 0s 12ms/sample - loss: 0.7470 - accuracy: 0.8636
Epoch 8/100
22/22 [==============================] - 0s 14ms/sample - loss: 0.7376 - accuracy: 0.8636
Epoch 9/100
22/22 [==============================] - 0s 12ms/sample - loss: 0.7284 - accuracy: 0.8636
Epoch 10/100
22/22 [====================

Epoch 81/100
22/22 [==============================] - 0s 12ms/sample - loss: 0.3736 - accuracy: 0.9545
Epoch 82/100
22/22 [==============================] - 0s 11ms/sample - loss: 0.3702 - accuracy: 0.9545
Epoch 83/100
22/22 [==============================] - 0s 17ms/sample - loss: 0.3667 - accuracy: 0.9545
Epoch 84/100
22/22 [==============================] - 0s 10ms/sample - loss: 0.3633 - accuracy: 1.0000
Epoch 85/100
22/22 [==============================] - 0s 11ms/sample - loss: 0.3599 - accuracy: 1.0000
Epoch 86/100
22/22 [==============================] - 0s 12ms/sample - loss: 0.3566 - accuracy: 1.0000
Epoch 87/100
22/22 [==============================] - 0s 11ms/sample - loss: 0.3533 - accuracy: 1.0000
Epoch 88/100
22/22 [==============================] - 0s 11ms/sample - loss: 0.3500 - accuracy: 1.0000
Epoch 89/100
22/22 [==============================] - 0s 14ms/sample - loss: 0.3467 - accuracy: 1.0000
Epoch 90/100
22/22 [==============================] - 0s 12ms/sample - lo

In [38]:
inputwords = "abcdefghijklmnopqrstuvwxyz"
pre_num=eval(input())
for i in range(pre_num):
    alphet=input("请输入字母:")
    alphet=[w_to_id[ch] for ch in alphet]
    alphet=np.reshape(alphet,(1,4))
    prediction=model.predict(alphet)
#     print(prediction)
    print("预测值："+inputwords[np.argmax(prediction)])

2
请输入字母:abcd
预测值：e
请输入字母:bcde
预测值：f


In [41]:
with open("./字符预测/Embedding/weights.txt","w") as fp:
    for v in model.trainable_variables:
        fp.write(str(v.name)+"\n")
        fp.write(str(v.shape)+"\n")
        fp.write(str(v.numpy())+"\n")