In [21]:
import tensorflow as tf
import numpy as np
import os
inputword="abcde"
w_to_id={"a":0,"b":1,"c":2,"d":3,"e":4}
id_to_onehot={0:[1,0,0,0,0],1:[0,1,0,0,0],2:[0,0,1,0,0],3:[0,0,0,1,0],4:[0,0,0,0,1]}
train_x=[id_to_onehot[w_to_id["a"]],id_to_onehot[w_to_id["b"]],id_to_onehot[w_to_id["c"]],id_to_onehot[w_to_id["d"]],id_to_onehot[w_to_id["e"]]]
train_y=[w_to_id["b"],w_to_id["c"],w_to_id["d"],w_to_id["e"],w_to_id["a"]]
train_x=np.reshape(train_x,(len(train_x),1,5))
train_x=train_x.astype(np.float)
train_y=np.array(train_y)
print(train_x)
print(train_y)

[[[1. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0.]]

 [[0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0.]]

 [[0. 0. 0. 0. 1.]]]
[1 2 3 4 0]


In [25]:
print(inputword[2])

c


In [22]:
np.random.seed(7)
np.random.shuffle(train_x)
np.random.seed(7)
np.random.shuffle(train_y)
tf.random.set_seed(7)

In [24]:
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.SimpleRNN(3))
model.add(tf.keras.layers.Dense(units=5,activation="softmax"))
checkpoint_save_path="./字符预测/checkpoint_save"
if os.path.exists(checkpoint_save_path+".index"):
    print("----load model---")
    model.load_weights(checkpoint_save_path)
pre_one_char_callbacks=tf.keras.callbacks.ModelCheckpoint(filepath=
                                                          checkpoint_save_path,
                                                          save_best_only=True,
                                                          save_weights_only=True,
                                                          monitor='loss')
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])

train_history = model.fit(train_x,train_y,
                          batch_size=32, 
                          epochs=100, 
                          callbacks=[pre_one_char_callbacks])
model.summary()
print(train_history)

----load model---
Train on 5 samples
Epoch 1/100
5/5 [==============================] - 4s 783ms/sample - loss: 0.9294 - accuracy: 1.0000
Epoch 2/100
5/5 [==============================] - 0s 52ms/sample - loss: 0.9280 - accuracy: 1.0000
Epoch 3/100
5/5 [==============================] - 0s 53ms/sample - loss: 0.9265 - accuracy: 1.0000
Epoch 4/100
5/5 [==============================] - 0s 53ms/sample - loss: 0.9251 - accuracy: 1.0000
Epoch 5/100
5/5 [==============================] - 0s 52ms/sample - loss: 0.9236 - accuracy: 1.0000
Epoch 6/100
5/5 [==============================] - 0s 46ms/sample - loss: 0.9222 - accuracy: 1.0000
Epoch 7/100
5/5 [==============================] - 0s 50ms/sample - loss: 0.9208 - accuracy: 1.0000
Epoch 8/100
5/5 [==============================] - 0s 50ms/sample - loss: 0.9193 - accuracy: 1.0000
Epoch 9/100
5/5 [==============================] - 0s 46ms/sample - loss: 0.9179 - accuracy: 1.0000
Epoch 10/100
5/5 [==============================] - 0s 47ms/sa

Epoch 82/100
5/5 [==============================] - 0s 57ms/sample - loss: 0.8146 - accuracy: 1.0000
Epoch 83/100
5/5 [==============================] - 0s 50ms/sample - loss: 0.8132 - accuracy: 1.0000
Epoch 84/100
5/5 [==============================] - 0s 50ms/sample - loss: 0.8119 - accuracy: 1.0000
Epoch 85/100
5/5 [==============================] - 0s 54ms/sample - loss: 0.8105 - accuracy: 1.0000
Epoch 86/100
5/5 [==============================] - 0s 51ms/sample - loss: 0.8091 - accuracy: 1.0000
Epoch 87/100
5/5 [==============================] - 0s 57ms/sample - loss: 0.8077 - accuracy: 1.0000
Epoch 88/100
5/5 [==============================] - 0s 49ms/sample - loss: 0.8063 - accuracy: 1.0000
Epoch 89/100
5/5 [==============================] - 0s 48ms/sample - loss: 0.8049 - accuracy: 1.0000
Epoch 90/100
5/5 [==============================] - 0s 53ms/sample - loss: 0.8035 - accuracy: 1.0000
Epoch 91/100
5/5 [==============================] - 0s 51ms/sample - loss: 0.8022 - accurac

In [27]:
# 进行预测：
pre_num=eval(input())
for i in range(pre_num):
    alphet=input("请输入字母:")
    alphet=id_to_onehot[w_to_id[alphet]]
    alphet=np.reshape(alphet,(1,1,5))
    prediction=model.predict(alphet)
    print("预测值："+inputword[np.argmax(prediction)])


4
请输入字母:a
预测值：b
请输入字母:b
预测值：c
请输入字母:c
预测值：d
请输入字母:d
预测值：e


In [28]:
# 参数的提取
with open("./字符预测/weights.txt","a") as fp:
    for r in model.trainable_variables:
        fp.write(str(r.name)+"\n")
        fp.write(str(r.shape)+"\n")
        fp.write(str(r.numpy())+"\n")