In [1]:
import tensorflow as tf
import numpy as np
a=np.arange(0,20).reshape(4,5)

In [2]:
#将numpy中的数组转换为张量
b=tf.convert_to_tensor(a,dtype=tf.float32)

In [3]:
b

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)>

In [4]:
a=tf.ones((2,3))#创建一个全为0的张量
b=tf.ones((2,3))#创建一个全为1的张量
c=tf.fill((2,3),9)#创建一个为指定数的张量
print(a)
print(b)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [5]:
# 生成正态分部的随机数，均值默认为0，方差默认为1,mean为均值，stddev是方差
a=tf.random.normal((2,3),mean=0,stddev=1.0)
print(a)
#生成截断式正态分布的随机数让其取值在（u-2*sigmoid,u+2*sigmoid）
tb=tf.random.truncated_normal((2,3),mean=0,stddev=1.0)
print(tb)

tf.Tensor(
[[ 1.2585145   0.42963192  0.293192  ]
 [ 0.7900816   0.626118   -0.8049505 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-1.959253   -1.4141572   1.8928362 ]
 [ 1.1724001  -0.4450207   0.50816816]], shape=(2, 3), dtype=float32)


In [6]:
#生成均匀分布的随机数,minval为最小值，maxval为最大值
tb=tf.random.uniform((2,3),minval=1.0,maxval=5.0)
print(tb)

tf.Tensor(
[[1.136795  2.8265448 4.1586647]
 [1.9512539 2.2380514 4.143064 ]], shape=(2, 3), dtype=float32)


In [8]:
a=tf.constant([[1,2,34],[1,4,5]])
print(a)

tf.Tensor(
[[ 1  2 34]
 [ 1  4  5]], shape=(2, 3), dtype=int32)


In [9]:
# 将a的int类型转为float类型
a=tf.cast(a,tf.float32)
#在纵向求a的最小值，axis=0表示纵向，axis=1表示横向
print(tf.reduce_min(a,axis=0))
#在横向求a的最大值
print(tf.reduce_max(a,axis=1))
#在a的横向求和
print(tf.reduce_sum(a,axis=1))
#在a的纵向求平均值
print(tf.reduce_mean(a,axis=0))

tf.Tensor([1. 2. 5.], shape=(3,), dtype=float32)
tf.Tensor([34.  5.], shape=(2,), dtype=float32)
tf.Tensor([37. 10.], shape=(2,), dtype=float32)
tf.Tensor([ 1.   3.  19.5], shape=(3,), dtype=float32)


In [10]:
x1=tf.ones((1,3),dtype=tf.float32)
x2=tf.fill((1,3),4.0,)
print(x1)
print(x2)

tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)
tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)


In [11]:
#加法
print(tf.add(x1,x2))
#减法
print(tf.subtract(x1,x2))
#乘法
print(tf.multiply(x1,x2))
#除法
print(tf.divide(x1,x2))
#几次方
print(tf.pow(x2,3))
#平方
print(tf.square(x2))
#开根号
print(tf.sqrt(x2))
#矩阵乘法
x3=tf.fill((3,1),5.0)
print(tf.matmul(x1,x3))

tf.Tensor([[5. 5. 5.]], shape=(1, 3), dtype=float32)
tf.Tensor([[-3. -3. -3.]], shape=(1, 3), dtype=float32)
tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.25 0.25 0.25]], shape=(1, 3), dtype=float32)
tf.Tensor([[64. 64. 64.]], shape=(1, 3), dtype=float32)
tf.Tensor([[16. 16. 16.]], shape=(1, 3), dtype=float32)
tf.Tensor([[2. 2. 2.]], shape=(1, 3), dtype=float32)
tf.Tensor([[15.]], shape=(1, 1), dtype=float32)


In [12]:
#切分传入张量的第一维度，生成输入特征/标签对，构建数据集'
features=tf.constant([12,23,56,1])
labels=tf.constant([1,0,1,0])
# data=tf.data.Dataset.from_tensor_slices((features,labels))
data=tf.data.Dataset.from_tensor_slices((x1,x2))
for i in data:
    print(i)
#print(data)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 4., 4.], dtype=float32)>)


In [13]:
# 求张量的梯度
with tf.GradientTape() as tp:
    w=tf.Variable(3.0)
    loss=tf.pow(w,2)
grad=tp.gradient(loss,w)
print(grad)


tf.Tensor(6.0, shape=(), dtype=float32)


In [14]:
w=tf.Variable(tf.constant(3.0))
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>


In [15]:
# enumerate可以遍历每个元素（如列表，元组，或者字符串），组合为：索引 元素,常在for循环中使用
seq=["one","two","three"]
for i,element in enumerate(seq):
    print(i,element)

0 one
1 two
2 three


In [16]:
labels=tf.constant([1,2,3,4,5])
output=tf.one_hot(labels,depth=6)
print(output)

tf.Tensor(
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]], shape=(5, 6), dtype=float32)


In [20]:
#tensorflow的用法相当于Java中的三目运算符
a=tf.constant([1,2,0,3,1,2])
b=tf.constant([0,1,5,6,7,1])
c=tf.where(tf.greater(a,b),a,b)#如果a>b，则返回a,如果a<b则返回b
print("c:",c)

c: tf.Tensor([1 2 5 6 7 2], shape=(6,), dtype=int32)


In [ ]:
#生成一个[0,1)的随机数

In [23]:
rdm=np.random.RandomState(seed=1)
a=rdm.rand()
b=rdm.rand(2,3)
print(a)
print(b)

0.417022004702574
[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [31]:

x,y=np.mgrid[1:3:0.5,2:4:0.5]
# 将多维数组拉直，变成一维的
print(x.ravel())
print(y.ravel())
#使返回的间隔数值点配对
print(np.c_[x.ravel(),y.ravel()])

[1.  1.  1.  1.  1.5 1.5 1.5 1.5 2.  2.  2.  2.  2.5 2.5 2.5 2.5]
[2.  2.5 3.  3.5 2.  2.5 3.  3.5 2.  2.5 3.  3.5 2.  2.5 3.  3.5]
[[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [1.5 2. ]
 [1.5 2.5]
 [1.5 3. ]
 [1.5 3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]
 [2.5 2. ]
 [2.5 2.5]
 [2.5 3. ]
 [2.5 3.5]]


In [2]:
# 交叉熵损失函数
loss1=tf.losses.categorical_crossentropy([1,0],[0.6,0.4])
loss2=tf.losses.categorical_crossentropy([1,0],[0.8,0.2])
print(loss1)
print(loss2)

tf.Tensor(0.5108256, shape=(), dtype=float32)
tf.Tensor(0.22314353, shape=(), dtype=float32)


In [4]:
a=tf.constant([[1,2,4],[4,5,6]])
print(a.numpy())

[[1 2 4]
 [4 5 6]]


In [10]:
a=tf.constant(["abc","bjccde","bjcde"])
print(tf.strings.length(a))
#长度不固定的张量表示为RaggedTensor.to_tensor转为普通的张量，填充的0在数字的后面
print(tf.strings.unicode_decode(a,"utf8"))
print(tf.strings.unicode_decode(a,"utf8").to_tensor().numpy())

tf.Tensor([3 6 5], shape=(3,), dtype=int32)
<tf.RaggedTensor [[97, 98, 99], [98, 106, 99, 99, 100, 101], [98, 106, 99, 100, 101]]>
[[ 97  98  99   0   0   0]
 [ 98 106  99  99 100 101]
 [ 98 106  99 100 101   0]]


In [13]:
#长度不固定的张量
a=tf.ragged.constant([[1,2,4],[5,5,7],[],[1,5,4,7,8,9]])
print(a.to_tensor().numpy())

[[1 2 4 0 0 0]
 [5 5 7 0 0 0]
 [0 0 0 0 0 0]
 [1 5 4 7 8 9]]


In [23]:
'''
让固定的位置上填写指定的值,其中的indices里面必须按着顺序，
否则在tf.sparse.to_dense就会报错

'''
a=tf.SparseTensor(indices=[[0,1],[1,3],[2,4]],
                  values=[1,2,4],
                  dense_shape=[4,5])
print(tf.sparse.to_dense(a).numpy())
b=tf.SparseTensor(indices=[[1,0],[0,0],[2,3]],
                  values=[1,2,4],
                  dense_shape=[3,4])
#对indices进行了重新排序操作
b=tf.sparse.reorder(b)
print(tf.sparse.to_dense(b).numpy())

[[0 1 0 0 0]
 [0 0 0 2 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]
[[2 0 0 0]
 [1 0 0 0]
 [0 0 0 4]]


In [33]:
#变量
a=tf.Variable([[1,2,4],[2,4,6]])
print(a.numpy())
#对a[1,2]赋值
a[1,2].assign(10)
print(a.numpy())
#对a[1]进行赋值
a[1].assign([1,1,1])
print(a.numpy())
#对a进行赋值
a.assign(2*a)
print(a.numpy())

[[1 2 4]
 [2 4 6]]
[[ 1  2  4]
 [ 2  4 10]]
[[1 2 4]
 [1 1 1]]
[[2 4 8]
 [2 2 2]]


In [37]:
c=tf.Variable(6)
print(c.numpy())
c.assign(10)
print(c.numpy())

6
10


In [38]:
a=tf.constant([[1,2,4],[4,5,6]])
b=tf.constant([[1],[2],[3]])
print(a @ b)

tf.Tensor(
[[17]
 [32]], shape=(2, 1), dtype=int32)
